### ISSUE TITLE
Adding cache to mongoose

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#11]
We need to do this, it doesn't make sense that 3-4 times in one request we try to get the user by Id...
There is a cache module that looks pretty easy - 

https://www.npmjs.com/package/mongoose-cachebox

**Comment by Yahavw** [comment]
I tried to add mongoose-cachebox to the League model, and then running the test with no local db, and there was no improvements, maybe I didn't use it properly, and the cache didn't take effect. There is more node.js cache solutions we can try.

**Comment by oreporan** [comment]
I think the only way to properly test it is by creating some test that gets a user two times and then gets the user two times directly from
The db or something...and compares times..

**Comment by Yahavw** [comment]
Did so. Added a new test file, for User model, and tried to play more with the mongoose, without any results. this is the test I wrote(didn't push):

```
/**
 * Test cache performance, should run with remote DB
 */
describe('#DbCache', function() {
    it('Create a user, then get that user by ID 4 time', function(done) {
        var userName = 'getUser';
        // Generate a user 
        var user = test.generateUser(userName);
        test.saveUserToDB(user, function(client1) {
            logger.test('DbCache', 'saved client1: ' + client1._id);

            User.getUserById(client1._id, function(err, client2) {
                logger.test('DbCache', ' client2 ID: ' + client2._id);

                User.getUserById(client2._id, function(err, client3) {
                    logger.test('DbCache', 'user2 found');

                    User.getUserById(client3._id, function(err, client4) {
                        logger.test('DbCache', 'user3 found');

                        expect(client4.name).to.eql(userName);

                        done();
                    });
                });
            });
        });
    });
});
```

**Comment by Yahavw** [comment]
Following the mongoose doc, I added this to the User function:

```
var mongooseCachebox = require('mongoose-cachebox');

//adding mongoose cachebox
var options = {
        cache: true, // start caching 
        ttl: 30 // 30 seconds 
};

mongooseCachebox(mongoose, options);
```

```
module.exports.getUserById = function( clientId , callback ) {
  User.findById(clientId, callback)
  .cache()
  .exec(function (err, docs) { /* ... */

      if (err) throw error;

      console.log(docs.ttl) // time left for expiration in ms 
      console.log(docs.stored); // timestamp this query was cached 
      console.log(docs);

    });
};
```

But got error: `Cannot read property 'cache' of undefined`

**Comment by Yahavw** [comment]
Looks like a known issue:
https://github.com/cayasso/mongoose-cachebox/issues/1

**Comment by oreporan** [comment]
fuck them...lets use a different cache

**Comment by oreporan** [comment]
I think we should use another cache, because I can see this taking a lot of time

**Comment by Yahavw** [comment]
I will try something else

**Comment by Yahavw** [comment]
Node-cache gave very good improvements. Now need to add the cache to all models.

**Comment by oreporan** [comment]
good
don't do the Game schema yet, because I'm going to remove it

**Comment by Yahavw** [comment]
👍

2015-10-12 17:00 GMT+03:00 oreporan notifications@github.com:

**Comment by Yahavw** [comment]
Should we cache the getUserByName and authenticateUser ? Because they exclude the password

**Comment by Yahavw** [comment]
Need to merge and then commit. Done with User cache, will move to League

**Comment by Yahavw** [comment]
Done

**Comment by oreporan** [comment]
:clap:  That was fast!

Maybe we can write a log only if it _is_ found in the cache?

**Comment by Yahavw** [comment]
Yes, I will remove the not found one.

2015-10-22 10:11 GMT+03:00 oreporan notifications@github.com:

**Comment by oreporan** [comment]
We don't need this either - 

`[INFO ][10/27/2015 17:55:23][wpCache.setById] object cached with id: 562e97080f3596b12fd023e2`

**Comment by oreporan** [comment]
`[INFO ][10/27/2015 18:7:29][wpCache.getById] object with id: 562e97080f3596b12fd023e2 not found in cache`
