### ISSUE TITLE
notification system

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#16]
Every user will eventually need a notification tab.
When a user wants to join a league, the admin will get a notification of a "joining request" from a user.
The user will get a notification "approved" when the admin approves.

The best way to do this is to add a notifications array (with read/unread and timestamp) in the user's schema. something like : 
`notifications: [{read: false, created: <date> , text: <String>}]`
But we need to a build a smart system that sends and receives and marks notifications.

You want to take this @Yahavw  ?

**Comment by Yahavw** [comment]
I can take it, lets talk on Saturday and see what we need and want to do in
the server, and how we can move on to the client. Maybe we can focus on the
hybrid and just make a skeleton native  for learning purpose.

2015-10-03 18:35 GMT+03:00 oreporan notifications@github.com:

**Comment by oreporan** [comment]
Started working on this - right now each user has an array of notification IDs which he needs to query (bulk query) to get the notification object. 
There is currently a notification sent out to the admins when a user has joined the league, and a notification is sent out to a user who has become an admin

**Comment by oreporan** [comment]
Notification system has a few notifications now - (addAdmin, addGame, joinLeague, leaveLeague..)
These eventually need to become actual ios/android notifications
