### ISSUE TITLE
issue with running mocha

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#18]
I made a new test directory under `models`, 
but to run mocha I need to be in `external` directory or in `models` 
How can we make it run straight from `lib` directory?

**Comment by oreporan** [comment]
ok the solution I found is to run it like this from `/lib`

`mocha --recursive .` (note the '.' at the end!)

I guess each of us will have to do it by ourselves..

**Comment by Yahavw** [comment]
Good job!
So can we close this?

2015-10-03 19:09 GMT+03:00 oreporan notifications@github.com:
