### ISSUE TITLE
change the cronjob game time

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#19]
right now its set to the date of the game, it should be ~2 hours before game time

**Comment by oreporan** [comment]
I think with this new refactoring, we will put the whole time system on hold.

Everything will be explicit.
make a game, make the teams, close the game etc. will all be done by the admin

In the future we will add cronjobs

**Comment by Yahavw** [comment]
Agree. Things will change many times. Should add it after some client
progress

2015-10-12 19:20 GMT+03:00 oreporan notifications@github.com:

**Comment by oreporan** [comment]
Closing this for now, right now - creating a new game will also create a match, but this match doesn't set off a cron
