### ISSUE TITLE
Make mongodb run locally on the machine

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#2]
It shouldn't be so hard, this link explains everything

http://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/

We need to make sure that we configure it the same on both our computers so we don't need to change things whenever we push/pull

**Comment by oreporan** [comment]
I made this a bug because potentially it can cause tests to fail if we both run them at the same time :) ben shesh..

**Comment by oreporan** [comment]
Ok, mine works locally, I changes the file `config-test.js` to also have a parameter `localdb`
there you can see the port I am using.

Also - in app.js I am now starting the same (localhost, 27017, weplay_test)

**Comment by oreporan** [comment]
@Yahavw  - when you are able to run it locally, please close this issue

**Comment by Yahavw** [comment]
Done, mongodb is running locally with the same port - 27017.
