### ISSUE TITLE
Parallelize server functions

### ISSUE THREAD

**Issue by Yahavw** [oreporan/wePlayMin#21]
The most important thing to do, to achieve performance improvement is to parallelize the server functions. before doing that we need to think what we can parallelize, because the parallel functions need to be independent, not sure if we can parallelize something but lets check it.
see:
https://engineering.gosquared.com/making-dashboard-faster

http://www.sitepoint.com/10-tips-make-node-js-web-app-faster/

**Comment by oreporan** [comment]
Nice
That async module is genius..
We should definently use this

**Comment by oreporan** [comment]
Everything that can be using async is working now.
It also has other methods:

`async.parallel`
`async.waterfall` - also good, it does one method after the other but much more efficiently then doing it manually. I used this also

**Comment by Yahavw** [comment]
cool

2015-10-17 17:49 GMT+03:00 oreporan notifications@github.com:
