### ISSUE TITLE
user roles

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#22]
Each user joins the league as - Player/Invite

**Comment by oreporan** [comment]
This is done and tested

**Comment by Yahavw** [comment]
Today?

2015-10-12 16:17 GMT+03:00 oreporan notifications@github.com:

**Comment by oreporan** [comment]
Ok this is actually more complex than I thought, so I'm re-opening.

Its easy to make a user choose if he is a invite or not when he joins a league.
But then when he wants to join a game, how do we decide if he can?

I think the ideal way is to let a invite in when a 'normal' player has decided that he is not playing - but this is not easy to do in code...

**Comment by oreporan** [comment]
This is done.
What will happen is this - 

Everyone (invites and normal players) can decide if they are attending, but if you are a 'invite' player, then when the `gameBuilder` makes the teams, you are taken only after all the normal players are in the teams.

This has also been tested and working
