### ISSUE TITLE
the game building algorithm

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#27]
@nirla  - interview question.

`invites = [<id>,<id>,<id>...]`
`players = [<id>,<id>,<id>...]`
`numOfPlayersPerTeam = X`

make the teams so that the 'invite' array only plays if we need them
I don't have a solution, just hoping one of you could do it cleaner than what I did...

**Comment by oreporan** [comment]
@Yahavw, @nirla - Any suggestions?

**Comment by Yahavw** [comment]
I will set a time to think about this.

2015-10-26 21:52 GMT+02:00 oreporan notifications@github.com:

**Comment by oreporan** [comment]
Right now we will let the admin make the teams, closing this for now (maybe forever)
