### ISSUE TITLE
create gameEndpoint external and controller

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#3]
I think the API for the endpoint should look like this:

// This must take a league_id as a parameter of the request
`createGame()`

`getGameById()`

// This must contain a league in the request
`getAllGames()`

I guess we will need more but this is enough for now

**Comment by oreporan** [comment]
Still need to do - `getAllGames()`, this will receive an array of gamesId and return the array of games from the DB
Also need to do - `getGameById()`

**Comment by oreporan** [comment]
Actually we are still missing these functions

**Comment by Yahavw** [comment]
Right, we need to finish the game's  API, and to test it

**Comment by oreporan** [comment]
Code written - need to do unit tests

**Comment by oreporan** [comment]
done

**Comment by Yahavw** [comment]
🙌

2015-10-03 16:08 GMT+03:00 oreporan notifications@github.com:
