### ISSUE TITLE
git brances

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#30]
Now that we have a client module and a server module
we should probably use branches

@nirla  and @Yahavw  - you guys will use client branch and I will use server branch, 
and once a week (or something) we will push to the master branch

http://stackoverflow.com/questions/1519006/how-do-you-create-a-remote-git-branch

**Comment by oreporan** [comment]
In the future we will also need clientside testing with angular - From what I see it looks exactly like the testing we did on the server @Yahavw 

https://docs.angularjs.org/guide/unit-testing

and when we push to the `master` branch we will run these e2e tests:

https://docs.angularjs.org/guide/e2e-testing

**Comment by oreporan** [comment]
we have branches now right? closing this...

**Comment by Yahavw** [comment]
Right, server client and master

2015-11-21 13:31 GMT+02:00 oreporan notifications@github.com:
