### ISSUE TITLE
Bug in Games (cache?)

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#31]
@Yahavw - the method `Game.getGamesListById()` has changed, something weird..its being called twice...
also there is a `logger.test` there that shouldn't be
I don't really get whats going on there, I think it could have happened because of the caching

anyways I guess there is a problem with the unit test because it didn't fail when it should

**Comment by oreporan** [comment]
Actually I see the unit test is failing...strange

**Comment by Yahavw** [comment]
We can close this,  right?

2015-11-04 22:25 GMT+02:00 oreporan notifications@github.com:

**Comment by oreporan** [comment]
You can leave it, i didnt fix it yet
