### ISSUE TITLE
Add to Server - Get my leagues by my client id

### ISSUE THREAD

**Issue by nirla** [oreporan/wePlayMin#38]
in order to display all of 'my leagues' when entering leagues tab there must be way to get all the leagues the user takes part in.
something like 'getMyLeagues(clientId)'

I think it will be best to return an array of league objects (anyway it wont be too big).

what do you think ?

**Comment by oreporan** [comment]
Well getUser gets you an array of your leagueIds.
Then getLeague gets you the leagueObject.
I tried to avoid doing APIs that get/set things based on "my"

**Comment by nirla** [comment]
ok makes sense... I'll do it through getUser
