### ISSUE TITLE
Double fields problem

### ISSUE THREAD

**Issue by oreporan** [oreporan/wePlayMin#9]
I see now that the the League schema has the field `users = []` but also the User schema has the field `leagues = []` 

So when we have the method `addUserToLeague` in the leagues Endpoint, we also need to add this league to the User schema...

Its kind of double data...is it a problem?

**Comment by Yahavw** [comment]
I'm not sure that this is a problem, it will give us a cross data capability. We definitely need to add the League to the user when doing addUserToLeague, maybe from the controller and not from the League model.

**Comment by oreporan** [comment]
Ok, this is working, we just need to make sure this is done in the controllers.

So if a User adds himself to a game, the users controller calls the Game model to add the user to the game, and then calls the User model to add this game to the user's active games.
